### ISSUE TITLE
Display images from active_storage

### ISSUE THREAD

**Issue by dixpac** [igorkasyanchuk/rails_pdf#14]
Hey! Awesome project!

What approach would you recommend to display images from `active_storage`

For example:
`<%= image_tag user.avatar %>`

This is the error I get with ☝️ 

<img width="1266" alt="Screenshot 2020-02-02 at 17 39 37" src="https://user-images.githubusercontent.com/7427365/73611537-12970000-45e3-11ea-9e3e-05215587b615.png">

✌️

**Comment by igorkasyanchuk** [comment]
Just added the instructions:

https://github.com/igorkasyanchuk/rails_pdf#acticestorage-integration

**Comment by igorkasyanchuk** [comment]
```
body
  header.clearfix
    #logo
      img(src="<%= ActiveStorage::Blob.service.send(:path_for, project.logo.key) %>")
    h1 <%= project.title %>
```
