### ISSUE TITLE
How to send model data?

### ISSUE THREAD

**Issue by varmad** [igorkasyanchuk/rails_pdf#8]
Hello,

How to send Rails modal data to the template?

Regards,
Varma

**Comment by igorkasyanchuk** [comment]
hi, 
what is "modal data"? Maybe model data?
Sample but without models: https://github.com/igorkasyanchuk/rails_pdf/blob/master/test/dummy/app/pdf/index/index.pug.erb#L22

Basically, you can write ruby code there

**Comment by varmad** [comment]
@igorkasyanchuk 

Example:
```
def report
    @invoice = Invoice.first

    RailsPDF.template("report2/invoice.pug.erb").render do |data|
      send_data(data, type: 'application/pdf', disposition: 'inline', filename: 'report.pdf')
    end
end
```
How do I access `@invoice` variable in `report2/invoice.pug.erb` file?

Regards,
Varma

**Comment by igorkasyanchuk** [comment]
Strange, it should work, 

Try to pass using locals, here is one PR: https://github.com/igorkasyanchuk/rails_pdf/pull/5 (use this branch in Gemfile)

which could help.

Let me know if it works and I'll release a new version

**Comment by varmad** [comment]
> Strange, it should work,
> 
> Try to pass using locals, here is one PR: #5 (use this branch in Gemfile)
> 
> which could help.
> 
> Let me know if it works and I'll release a new version

Yes, it is working.

**Comment by igorkasyanchuk** [comment]
try to use new version just released, syntax is: 

`RailsPDF.template("index/index.pug.erb").locals(user: User.first).render do |data|`

**Comment by varmad** [comment]
> try to use new version just released, syntax is:
> 
> `RailsPDF.template("index/index.pug.erb").locals(user: User.first).render do |data|`

Perfect, it's working. 

Thank you so much for your help.
